cache: pip
install:
  - yes | pip uninstall py pytest
  - python setup.py install
jobs:
  include:
    - install: pip install black flake8 pydocstyle
      python: 3.6
      script:
        - black --check -l 79 .
        - flake8
        - pydocstyle bernard
language: python
matrix:
  fast_finish: true
python:
  - 3.5
  - 3.6
sudo: false
script:
  - python setup.py test
