cache: pip
install:
  - yes | pip uninstall py pytest
  - pip install flake8 pydocstyle
  - python setup.py install
language: python
matrix:
  fast_finish: true
python:
  - 3.5
  - 3.6
sudo: false
script:
  - flake8
  - pydocstyle bernard
  - python setup.py test
